Dockerfile
Makefile
docker-compose.vm.yml
nginx.conf

- Fix Dockerfile runner stage
- Update Makefile with targets to build and push image to GHCR. Registry is here: https://github.com/superplanehq/superplane/pkgs/container/superplane
- Add a `docker-compose.vm.yml` file that we can use to have a shared instance of the application

build: push image to GHCR

---

web_src/src/pages/canvas/store/canvasStore.ts

update outdated approve param naming in ui

fix: update outdated approve param naming in ui

---

web_src/src/pages/canvas/components/tabs/SettingsTab.tsx

Created ui to display inputs and ouputs.
Input mappings are also displayed within the Inputs.
It handles static values or stage-referenced inputs from ValueFrom.
https://github.com/user-attachments/assets/26d8f448-434f-4475-a824-e569f7723478

feat: add inputs and outputs to UI

---

web_src/src/pages/canvas/utils/flowTransformers.ts

- Remove red connections color
- Fix null date

refactor: remove red connections color and fix null date

---

web_src/src/pages/canvas/components/tabs/RunItem.tsx

Fix `npm run build` command  by fixing export name

fix: execution result export name

---

.semaphore/semaphore.yml

- Added Frontend build CI block to test its build before trigerring the promotion

feat: create front end build CI job

---

pkg/authentication/authentication.go
pkg/models/account.go
web_src/src/pages/auth/OrganizationSelect.tsx

From this:
To this:
Also fix an issue with the pending invitations query.

fix: refactor organization selection page

---

web_src/src/pages/canvas/components/StageEditModeContent.tsx

fix for payload input for http stage that was not possible to use

fix: payload input for http stage

---

web_src/src/pages/canvas/components/EventStateItem.tsx
web_src/src/pages/canvas/components/MessageItem.tsx
web_src/src/pages/canvas/components/QueueItems.tsx
web_src/src/pages/canvas/components/SideBar.tsx
web_src/src/pages/canvas/components/StageEditModeContent.tsx
web_src/src/pages/canvas/components/StageQueueSection.tsx
web_src/src/pages/canvas/components/nodes/IOTooltip.tsx
web_src/src/pages/canvas/components/nodes/connection_group.tsx
web_src/src/pages/canvas/components/nodes/event_source.tsx
web_src/src/pages/canvas/components/nodes/stage.tsx
web_src/src/pages/canvas/components/tabs/RunItem.tsx
web_src/src/pages/canvas/utils/inputMappingHandlers.ts
web_src/src/pages/canvas/utils/stageEventUtils.ts

This PRs enhances Input mapping validation adding proper error handling and usability to work just like the Yaml.
In this PR, we also modularized and updated the design of queue items.
+ minor fixes

refactor: input mapping validation and design

---

web_src/src/pages/canvas/components/EventItem.tsx
web_src/src/pages/canvas/components/EventSourceSidebar.tsx
web_src/src/pages/canvas/components/ExecutionTimeline.tsx
web_src/src/pages/canvas/components/MessageItem.tsx
web_src/src/pages/canvas/components/SideBar.tsx
web_src/src/pages/canvas/components/nodes/stage.tsx
web_src/src/pages/canvas/components/tabs/ActivityTab.tsx
web_src/src/pages/canvas/components/tabs/HistoryTab.tsx
web_src/src/pages/canvas/components/tabs/RunItem.tsx

- Improved the Event source sidebar and its event item
- Improve RunItem and Message item for Stage Sidebar

Improvement(ui): sidebar and node design

---

pkg/grpc/actions/canvases/delete_canvas_test.go
pkg/models/canvas.go

[fix: conflicting canvas name after deletion](https://github.com/superplanehq/superplane/commit/d91fe69bcec46d3c411b09a8f79ee0da6a23dc97)

fix: conflicting canvas name after deletion

---

web_src/src/components/Badge/badge.tsx
web_src/src/components/SettingsPage/components/CanvasIntegrations.tsx
web_src/src/pages/canvas/components/EventSourceBadges.tsx
web_src/src/pages/canvas/components/EventSourceZeroState.tsx
web_src/src/pages/canvas/components/EventTriggerBadge.tsx
web_src/src/pages/canvas/components/FlowRenderer.tsx
web_src/src/pages/canvas/components/StageEditModeContent.tsx
web_src/src/pages/canvas/components/nodes/event_source.tsx
web_src/src/pages/canvas/components/nodes/stage.tsx
web_src/src/pages/canvas/types/flow/index.ts
web_src/src/pages/canvas/utils/flowTransformers.ts

- Added source info badge about the event
- Running event should show the current event id
- Fixed truncation of badges
- Implemented badge tooltip
- Fixed Event Source zero state descriptions and modularized it
- Fixed icons for canvas integration page and ui

improvement: Metadata shown and Info Badges

---

pkg/public/ws/ws_hub.go
web_src/src/pages/canvas/hooks/useWebsocketEvents.ts

This reverts commit 193dd698b476a94dfb08ea18184f2debd723f5ad.

revert:  "feat: implement simple hearbeat (#174)"

---

web_src/src/pages/canvas/components/SidebarItem.tsx

Fixes https://github.com/superplanehq/superplane/issues/222

fix: new component button should be clickable

---

web_src/src/pages/canvas/components/nodes/event_source.tsx

refactor: Change default name from Listen to Listen to:

refactor: Change default name from Listen to Listen to:

---

web_src/src/pages/canvas/components/ConnectionGroupEditModeContent.tsx
web_src/src/pages/canvas/components/EventSourceEditModeContent.tsx
web_src/src/pages/canvas/components/StageEditModeContent.tsx
web_src/src/pages/canvas/store/canvasStore.ts
web_src/src/pages/canvas/utils/flowTransformers.ts

- [fix: clicking in any part of the components should select it](https://github.com/superplanehq/superplane/commit/6ae40ae65833a3f4aca1d018c6b038add7fb4217)
- [fix: overlapping issue by prioritizing editing or focused node](https://github.com/superplanehq/superplane/commit/c5cbf822484e98f22ba80e4b40b3ee4f07584dbe)

fix: overlapping nodes

---

AGENTS.md
CLAUDE.md
web_src/src/pages/canvas/index.tsx

See [this comment](https://github.com/superplanehq/superplane/issues/231#issuecomment-3306335396)

fix: once user opens component sidebar, keep it open

---

web_src/src/pages/canvas/components/ConnectionGroupEditModeContent.tsx
web_src/src/pages/canvas/components/EventSourceEditModeContent.tsx
web_src/src/pages/canvas/components/StageEditModeContent.tsx
web_src/src/pages/canvas/store/canvasStore.ts
web_src/src/pages/canvas/utils/flowTransformers.ts

This reverts commit 0cd4ae20051c844a78a7a16a86d34e574f0cf25f.

Revert "fix: overlapping nodes (#275)"

---

Makefile

`docker-compose` is the older way of using docker compose

fix: always 'docker compose' instead of 'docker-compose' in Makefile

---

web_src/src/pages/canvas/components/EditModeActionButtons.tsx
web_src/src/pages/canvas/components/nodes/connection_group.tsx
web_src/src/pages/canvas/components/nodes/event_source.tsx
web_src/src/pages/canvas/components/nodes/stage.tsx
web_src/src/pages/canvas/store/canvasStore.ts
web_src/src/pages/canvas/store/types.ts
web_src/src/pages/canvas/utils/nodeDuplicationUtils.ts

feat: add duplicate button in the top of components actions bar

feat: create duplicate button for components

---

AGENTS.md
web_src/.gitignore
web_src/.storybook/main.ts
web_src/.storybook/preview.ts
web_src/AGENTS.md
web_src/eslint.config.js
web_src/package-lock.json
web_src/package.json
web_src/src/components/Badge/Badge.stories.tsx
web_src/src/components/Button/Button.stories.tsx
web_src/src/components/Button/button.tsx
web_src/src/components/Checkbox/Checkbox.stories.tsx
web_src/src/components/Checkbox/checkbox.tsx
web_src/src/components/Input/Input.stories.tsx
web_src/src/components/Switch/Switch.stories.tsx
web_src/src/components/Switch/switch.tsx

Create the initial storybook configuration for having storybook to help us develop our UI components. This pull request only pulls the storybook libraries and creates a couple of storybook stories for our most basic components (button, checkbox, input, ...). This allow us to start using that for new components, and enables us to start refactoring the current components we have to follow this same pattern.

toil(ui): initial setup for storybook

---

web_src/src/pages/canvas/components/StageEditModeContent.tsx

When I first create the stage, the message `"At least one connection is required"` appears (this is correct).  
After I add a connection, the "Connections" label is no longer red, but the error message still remains even though the connection is configured.
The error message should disappear at the same time when the "Connections" label changes color.

fix: error message should disappear after re-validation

---

pkg/workers/hard_deletion_worker.go
pkg/workers/hard_deletion_worker_test.go

- Keep plain events from deleted sources
Related Issue: https://github.com/superplanehq/superplane/issues/279

refactor: keep plain events from deleted sources

---

web_src/src/components/CreateCanvasModal/CreateCanvasModal.stories.tsx
web_src/src/components/CreateCanvasModal/CreateCanvasModal.tsx

Issue: https://github.com/superplanehq/superplane/issues/317

feat: add validation to the canvas modal

---

Makefile
pkg/grpc/actions/stages/update_stage.go
web_src/src/pages/canvas/components/StageEditModeContent.tsx
web_src/src/pages/canvas/components/nodes/stage.tsx

Fixes issues raised in [this comment](https://github.com/superplanehq/superplane/issues/226#issuecomment-3337242586)  and [this other comment](https://github.com/superplanehq/superplane/issues/226#issuecomment-3337585580).

fix: hide dry-run toggle for no-op + fix stage update when using it
